#+title: Log

* 2023/08/13

- Implementei uma correção inicial para o bug #1747 do projeto logisim evolution.
  Parte considerável do tempo foi gasto com a fricção inicial do projeto, como entender o
  workflow e guidelines de contribuição, instalação da IDE, configuração do projeto gradle, entre outros.
  Tempo gasto: 4 horas.
  [[https://github.com/logisim-evolution/logisim-evolution/pull/1824][Link]]


* 2023/08/14

** 08:00 - 08:15
- Apliquei uma modificação de linting requsitada na pull request do dia anterior.
  Tempo gasto: 15 minutos.
  [[https://github.com/logisim-evolution/logisim-evolution/pull/1824/commits/30ad0b062c5aeb9cd05bee16be4fd615e51cd61d][Link]]

*  2023/08/18

** 19:00 às 22:00
- Comecei a trabalhar em correções das issues #7172 e #6981 do projeto fish-shell.
- Enviei uma Pull Request sobre o a issue #6981 do projeto. [[https://github.com/fish-shell/fish-shell/pull/9965][Link]]
  Tempo gasto: 3 horas.

* 2023/08/19

** 07:00 às 09:00
- Comecei a trabalhar na issue #1338 do projeto logisim-evolution.
- Abri uma pull request corrigindo os problemas descritos na issue. [[https://github.com/logisim-evolution/logisim-evolution/pull/1830][Link]]
Tempo gasto: 2 horas.

* 2023/08/25

** 20:00 às 22:40
- Comecei a desenvolver uma solução para a issue #1716 do projeto logisim-evolution. [[https://github.com/logisim-evolution/logisim-evolution/pull/1835][Link]]
Tempo gasto: 2 horas e 20 minutos.

* 2023/08/26

** 10:00 às 10:30, 19:00 às 20:00, 23:00 às 23:40
- Comecei a trabalhar na issue #1510 do projeto logisim-evolution.
Tempo gasto: 2 horas e 10 minutos.

* 2023/09/01

** 11:30 ao 12:00
- Consertei os ajustes requisitados na issue #1835 do logisim evolution. [[https://github.com/logisim-evolution/logisim-evolution/pull/1835][Link]]
Tempo gasto: 30 minutos.

** 12:30 às 13:30
- Continuei a trabalhar na issue #1716 do projeto logisim-evolution. TODO: Link Commit
  Tempo gasto: 1 hora.

* 2023/09/04

** 11:20 - 12:40, 13:00 - 13:50
- Continuei a trabalhar na issue #1716 do projeto logisim evolution e abri
  a draft de pull request. [[https://github.com/logisim-evolution/logisim-evolution/pull/1844][Link]]
  Tempo gasto: 2 horas e 10 minutos.

* 2023/09/07

** 08:40 - 09:40
- Diagnostiquei e testei o projeto para encontrar os problemas reportados na issue #1841 do projeto
  logisim-evolution. [[https://github.com/logisim-evolution/logisim-evolution/issues/1841][Link]]
  Tempo gasto: 1 hora.

** 10:00 - 12:00
- Comecei a implementação do output enable inversível (issue #1716) para o componente de RAM do
  logisim evolution.
  Tempo gasto: 2 horas.

* 2023/09/08

** 14:30 - 15:00
- Consertei os erros de encoding da issue #1815 do projeto logisim-evolution.
  Tempo gasto: 1 hora e 30 minutos.

* 2023/09/10

** 22:30 - 01:00
- Implementei uma corerção para a issue #1510 do projeto logisim-evolution.[[https://github.com/logisim-evolution/logisim-evolution/pull/1855][ Link]]
  Tempo gasto: 2 horas e 30 minutos.

** 12:00 - 12:15
- Atualizei as styles changes da minha última pull request
  Tempo gasto: 15 minutos.

** 15:00 - 15:20
- Implementei as mudanças requisitadas na última pull request
  Tempo gasto: 20 minutos.

* 2023/09/11

** 10:00 - 11:05
- Implementei melhorias de estilo para a classe Value.java do projeto logisim-evolution. [[https://github.com/figurantpp/logisim-evolution/commit/e6a4e5f501197fbb07f5bb1505835734f0][Link]]
  Tempo gasto: 1 hora e 5 minutos.

* 2023/09/12

- Implementei as mudanças de nome requisitadas na pull request de RAM enable.
  Tempo gasto: 1 hora.
  TODO: Add link e horário

* 2023/09/13
** 18:00 - 19:00
- Ajustei os problemas de lint vindos da ultima pull request.
- Comecei a implementar javadocs para a classe Value do logisim-evolution.
  Tempo gasto: 1 hora.

* 2023/09/16
** 18:00 - 18:15
- Terminei de ajustar e enviei a pull request 1863
  Tempo gasto: 15 minutos.

** 18:15 - 19:15
- Comecei a estudar o VHDL no logisim-evolution para conseguir melhorar a pull reuqest de cabos na RAM.
  Tempo gasto: 1 hora.

* 2023/09/19
** 16:00 - 18:00
- Comecei a depurar o projeto para implementar um fix para a issue [[https://github.com/clj-kondo/clj-kondo/issues/2013][#2013]] do projeto clj-kondo.
- Comtinuei a documentar o package logisim.data do projeto logisim-evolution.
  Tempo gasto: 2 horas.

* 2023/09/20
** 17:00 - 19:00
- Implementei modificações de javadoc como requisitado na pull request [[https://github.com/logisim-evolution/logisim-evolution/pull/1863][#1863]] do logisim-evolution.
  Tempo gasto: 2 horas.

* 2023/09/22

** 10:30 - 13:00
- Melhorei a documentação de javadoc das classes Value.java e TestVector.java da pull request 1863 do projeto logisim-evolution.
  Tempo gasto: 2 horas e 30 minutos.

* 2023/09/23
** 21:40 - 22:00
- Terminei de documentar as clases TestVector e Value do logisim evolution
- Comecei a documentação a classe ~Attributes~ do projeto logisim evolution.
  Tempo gasto: 1 hora e 20 minutos.

* 2023/09/27
** 16:00 - 18:00
- Terminei a onda inicial de documentaççao da classe Attributes.
- Comecei da documentar a classe Attribute.
  Tempo gasto: 2 horas.

* 2023/10/02
** 09:00 - 10:30
- Terminei de documentar a classe Attributes.
- Comecei a documentar a interface AttributeSet e Attribute.
  Tempo gasto: 1 hora e 30 minutos.

** 13:00 - 14:00
- Continuei a documentação da classe Attribute, procurando o comportamento
  de certas partes da API.
  Tempo gasto: 1 hora.

* 23:00 - 00:40
- Continuei a documentar a interface AttributeSet do logisim evolution.
  Aprendi que documentar interfaces, pode ser muito mais demorado que documentar classes,
  especialmente porque se deve olhar diversas implementações da interface e conseguir traçar
  os comportamentos em comum e variados para descobrir quais contratos são enforçados pela API da
  interface.
  Tempo gasto: 1 hora e 40 minutos.

* 2023/10/09
** 13:30 - 15:00
- Continuei a documentação da classe AttributeSet, especialmente em relação aos contratos dos atributos read only desta interface.
  Tempo gasto: 1 hora e 30 minutos.

* 2023/10/10
** 19:30 - 20:00, 21:30 - 22:00
- Teminada a documentação da interface AttributeSet
  Tempo gasto: 1 hora.

* 2023/10/18
** 22:30 - 23:00
Comecei a documentar a classe Location do projeto logisim evolution.
A maior parte do tempo foi gasto documentando o comportamento da função parse do projeto.
Tempo gasto: 30 minutos.

* 2023/10/19
** 09:30 - 11:00
Continuei a investigação da issue #2013 do clj-kondo.
Tempo gasto: 1 hora e 30 minutos.

* 2023/10/20
** 17:00 - 19:00
- Terminei o debugging da issue #2013 do clj-kondo.
- Consegui determinar mais casos que causam o problema da issue.
- Implementei uma solução para a issue
  Tempo gasto: 2 horas

* 2023/10/22
** 06:20 - 07:20
- Comecei a estudar o modelo de teste do clj-kondo para implementar os testes para
  o fix implementado no dia anterior.
  Tempo gasto: 1 hora

* 2023/10/23
** 12:00 - 12:40
- Implementei os testes para o fix implementado.
  Tempo gasto: 40 minutos

* 2023/10/24
** 17:20 - 17:40
- Implementei as modificações requisitadas na pull request anterior.
  Tempo gasto: 20 minutos.

* 2023/10/27
** 10:30 - 11:00
- Continuei a documentação da classe Location do logism evolution.
  Tempo gasto: 30 minutos

* 2023/10/28
** 10:00 - 12:00
- Terminei de documentar a classe Location do logisim evolution.
  Parte considerável do tempo foi gasto documentando os métodos `rotate` e `translate`
  que tem comportamentos geométricos não muito óbvios, e requerem documentação boa.
  Tempog gasto: 2 horas.

** 22:30 - 00:00
- Documentei as classes ~AttributeDefaultProvider~,
  ~AttributeEvent~, ~AttributeListener~, ~AttributeOption~, ~AttributeOptionInterface~
  do logisim evolution

  Tempo gasto: 1 hora e 30 minutos.

* 2023/10/29
** 10:30 - 13:00
- Removi redundâncias em relação aos campos ~@return~ dos javadocs dos getters.
- Documentei as classes ~Direction~, ~FailException~, ~TestException~
  ~Direction~, ~BitWidth~ do projeto.
  Tempo gasto: 2 horas e 30 minutos.

* 2023/10/30
** 20:00 - 21:30
- Melhorei a documentação do método ~rotate~
- Comecei a documentar a classe ~Bounds~, também precisando de explicações detalhadas para operações
  gemétricas.
  Tempo gasto: 1 hora e 30 minutos

* 2023/10/31
** 18:20 - 19:20
- Continuei a documentação da classe ~Bounds~ do projeto.
  Tempo gasto: 1 hora.

* 2023/11/1
** 19:00 - 20:00
- Continuei a documentação da a classe ~Bounds~ do projeto.
  Com esta terminada, faltará documentar a classe ~AbstractAttributeSet~
  Tempo gasto: 1 hora.

* 2023/11/2
** 19:40 - 20:50
- Terminei de documentar a classe ~Bounds~ e ~AbstractAttributeSet~ do projeto
  Tempo gasto: 1 hora e 10 minutos.

** 21:00 - 21:40
- Refatorações (style lint da pull request) e revisão da documentação implementada
  Tempo gasto: 40 minutos.

** 21:40 - 22:20
- Montei uma lista de problemas no código que documentei na pull request, e removi
  certos TODOs que eu tinha deixado no código.
  A pull request está agora aberta para merge.
  Tempo gasto: 40 minutos.

* 2023/11/3
** 14:00 - 15:00
- Ajudei a adicionar a guia academics do site do flusp com o João Paulo
  Tempo gasto: 1 hora.

** 21:00 - 23:00
- Corrigi a issue [[https://github.com/clj-kondo/clj-kondo/issues/1753][#1753]] do projeto clj-kondo.
  Tempo gasto: 2 horas.

* 2023/11/4
** 11:30 - 13:40
- Comecei a implementar uma correção para a issue [[https://github.com/nushell/nushell/issues/10175][#10175]] do projeto nushell.
  Tempo gasto: 2 horas e 10 minutos.

* 2023/11/5
** 11:00 - 11:30, 13:20 - 14:20
- Continuei a investigação da issue do projeto, encontrei o problema relatei na issue.
  Tempo gasto: 1 hora e 30 minutos.
